\hypertarget{classdjango_1_1core_1_1exceptions_1_1_multiple_objects_returned}{}\doxysection{django.\+core.\+exceptions.\+Multiple\+Objects\+Returned Class Reference}
\label{classdjango_1_1core_1_1exceptions_1_1_multiple_objects_returned}\index{django.core.exceptions.MultipleObjectsReturned@{django.core.exceptions.MultipleObjectsReturned}}


Inheritance diagram for django.\+core.\+exceptions.\+Multiple\+Objects\+Returned\+:
% FIG 0


Collaboration diagram for django.\+core.\+exceptions.\+Multiple\+Objects\+Returned\+:
% FIG 1


\doxysubsection{Detailed Description}
\begin{DoxyVerb}The query returned multiple objects when only one was expected.\end{DoxyVerb}
 

The documentation for this class was generated from the following file\+:\begin{DoxyCompactItemize}
\item 
venv/\+Lib/site-\/packages/django/core/exceptions.\+py\end{DoxyCompactItemize}
