\hypertarget{classdjango_1_1db_1_1utils_1_1_database_error_wrapper}{}\doxysection{django.\+db.\+utils.\+Database\+Error\+Wrapper Class Reference}
\label{classdjango_1_1db_1_1utils_1_1_database_error_wrapper}\index{django.db.utils.DatabaseErrorWrapper@{django.db.utils.DatabaseErrorWrapper}}
\doxysubsection*{Public Member Functions}
\begin{DoxyCompactItemize}
\item 
def \mbox{\hyperlink{classdjango_1_1db_1_1utils_1_1_database_error_wrapper_a24bcae5337ae932f0c49f1304d8ee6df}{\+\_\+\+\_\+init\+\_\+\+\_\+}} (self, wrapper)
\item 
\mbox{\Hypertarget{classdjango_1_1db_1_1utils_1_1_database_error_wrapper_a8921a9c774d09294bda1add2dea16793}\label{classdjango_1_1db_1_1utils_1_1_database_error_wrapper_a8921a9c774d09294bda1add2dea16793}} 
def {\bfseries \+\_\+\+\_\+enter\+\_\+\+\_\+} (self)
\item 
\mbox{\Hypertarget{classdjango_1_1db_1_1utils_1_1_database_error_wrapper_aa6030eca66c946b41adf23999b141f69}\label{classdjango_1_1db_1_1utils_1_1_database_error_wrapper_aa6030eca66c946b41adf23999b141f69}} 
def {\bfseries \+\_\+\+\_\+exit\+\_\+\+\_\+} (self, exc\+\_\+type, exc\+\_\+value, traceback)
\item 
\mbox{\Hypertarget{classdjango_1_1db_1_1utils_1_1_database_error_wrapper_a5db1e27680fe82c17bf945e2b7fdf791}\label{classdjango_1_1db_1_1utils_1_1_database_error_wrapper_a5db1e27680fe82c17bf945e2b7fdf791}} 
def {\bfseries \+\_\+\+\_\+call\+\_\+\+\_\+} (self, func)
\end{DoxyCompactItemize}
\doxysubsection*{Public Attributes}
\begin{DoxyCompactItemize}
\item 
\mbox{\Hypertarget{classdjango_1_1db_1_1utils_1_1_database_error_wrapper_a6e49a03de1f29b7f126c7c6223f6765e}\label{classdjango_1_1db_1_1utils_1_1_database_error_wrapper_a6e49a03de1f29b7f126c7c6223f6765e}} 
{\bfseries wrapper}
\end{DoxyCompactItemize}


\doxysubsection{Detailed Description}
\begin{DoxyVerb}Context manager and decorator that reraises backend-specific database
exceptions using Django's common wrappers.
\end{DoxyVerb}
 

\doxysubsection{Constructor \& Destructor Documentation}
\mbox{\Hypertarget{classdjango_1_1db_1_1utils_1_1_database_error_wrapper_a24bcae5337ae932f0c49f1304d8ee6df}\label{classdjango_1_1db_1_1utils_1_1_database_error_wrapper_a24bcae5337ae932f0c49f1304d8ee6df}} 
\index{django.db.utils.DatabaseErrorWrapper@{django.db.utils.DatabaseErrorWrapper}!\_\_init\_\_@{\_\_init\_\_}}
\index{\_\_init\_\_@{\_\_init\_\_}!django.db.utils.DatabaseErrorWrapper@{django.db.utils.DatabaseErrorWrapper}}
\doxysubsubsection{\texorpdfstring{\_\_init\_\_()}{\_\_init\_\_()}}
{\footnotesize\ttfamily def django.\+db.\+utils.\+Database\+Error\+Wrapper.\+\_\+\+\_\+init\+\_\+\+\_\+ (\begin{DoxyParamCaption}\item[{}]{self,  }\item[{}]{wrapper }\end{DoxyParamCaption})}

\begin{DoxyVerb}wrapper is a database wrapper.

It must have a Database attribute defining PEP-249 exceptions.
\end{DoxyVerb}
 

The documentation for this class was generated from the following file\+:\begin{DoxyCompactItemize}
\item 
venv/\+Lib/site-\/packages/django/db/utils.\+py\end{DoxyCompactItemize}
